steps:
  - label: 'Formatting'
    commands:
      - .buildkite/bin/check-formatting

  - label: 'Ruby - 3.4.5'
    commands:
      - .buildkite/bin/test-ruby 3.4.5

  - label: 'Taylor - v0.3.14.1'
    commands:
      - .buildkite/bin/test-taylor v0.3.14.1
